- deployment/Staticfile
- stackato.yml
Since we can't auto deploy a Stackato app in response to commits to the repo, we instead have to perform these gymnastics. We don't |stackato push| our source directory, since it will get stale (and we need the .git directory, which isn't ideal to upload). As such we |stackato push| only the Staticfile, and clone the repo as part of the deploy.
Some other notes:
* We are having to use the legacy stackato.yml syntax, since the Mozilla instance is running an older v2.x Stackato release.
* The staticfiles buildpack we're using has a few bugs, so we're using my fork of it until upstream merges my PRs.
* The cron that we use to update the repo only runs on instance #0, so we limit the number of instances to one, since any others wouldn't self-update.
* We set app-dir to be a subdirectory of …
> Bug 1050477 - Add configuration files for Stackato

- stackato.yml
Now that the PRs fixing some issues have been merged to upstream, we no longer need to use my fork of the buildpack.
> Bug 1050477 - Stackato: Switch back to the upstream staticfile buildpack

- thirdparty/bzjs/bz-0.3.0.js
This switches all of the bzAPI uses but the /configuration call to use the native REST API.
> Bug 924405 - Replace bz.js/bzAPI usage with native Bugzilla REST API

- README.md
- css/style.css
- index.html
- js/BugData.js
- js/Remapper.js
- js/Step.js
- js/bugherder.js
- stackato.yml
This renames most uses of the string "mcMerge" with "Bugherder" in the repository. It leaves most of stackato.yml untouched as the deployed location has not yet been updated.
> Bug 1145836 - Rename mcMerge to Bugherder

- js/Config.js
- js/FlagLoader.js
This fixes various issues with setting release branch flags:
First, this fixes setting ESR status/tracking flags so they actually get set.
Second, this adds some new code to deal with setting the firefox38.0.5 flags for the next couple of months. (We'll want to revert this once 39 ships, though I think the Date checks I put in should make things revert to normal behavior once it ships.)
Next, it adds support for the esr38 repos that are in the process of being added.
Finally, it should hopefully make Bugherder able to process b2g release branches. This doesn't fix setting b2g release branch flags yet, but I might wait for some other Bugherder changes (being able to manually set flags, etc) before I deal with them.
> Bug 1154718 - Improve release branch flag handling

- js/FlagLoader.js
Pretty sure we need to replace the '.'s with '_'s in the flag name for the API call.
> Fix 38.0.5 flags, hopefully

- js/Config.js
- js/FlagLoader.js
- js/bugherder.js
I believe this will work, and should be obvious and easy enough to add/remove future b2g release versions as needed.
I don't know if that last chunk is actually needed, but I don't believe the tracking_ flags exist for b2g bugs, and I don't know how well Bugzilla's API deals with non-existent flags being messed with, so I just don't generate them at all.
> Bug 1160697 - Try to get b2g flags working

- js/Step.js
I think this is all that's needed.
> Bug 1166865 - Make status flags get set when they were previously set to '?'

- stackato.yml
* Use a fork of staticfile-buildpack since upstream master is broken for
older Stackato instances.
* Change url to allizom instance, since the mozilla one appears broken
for now.
> Bug 1183368 - Fix the Stackato deployment

- css/style.css
- index.html
Throws everything in a wrapper div, with enough bottom padding to accomodate the footer, and absolutely positions the footer at the bottom. Also, let's be semantically correct and use the footer tag.
> Bug 1190358: Push footer to the bottom of page when displaying changeset form

- karma.conf.js
- test/SpecRunner.html
- test/mySpec.js
This adds a few tests for functions defined in FlagLoader.js.
There's a test for generating flags for a "firefox39" tree (which doesn't exist, but the flags for it do).
There's a test for generating flags for the "b2g_2_0" tree (which isn't an actual tree, but it's what the flags are called).
There's a test for running the entire FlagLoader.js init function for the "mozilla-b2g32_v2_0" tree (which is what the "b2g_2_0" flags are connected to).
There's a test for running the entire init function for the "mozilla-esr38" tree (which uses the "firefox_esr38" flags).
There's tests for running the entire init function for the "mozilla-central" and "mozilla-aurora" trees (which use version-specific flags based on config files in-tree, requiring network requests to obtain).
> Add some tests for FlagLoader.js

- js/Step.js
So, it turns out, failed login attempts return a 401 error, not a 400 error, and the code only looked for 400 errors previously.
> Bug 1028922 - Make Bugherder actually abort the submit attempt if the user/pass is incorrect

- js/PushData.js
- js/Step.js
I haven't really tested this much with marking larger pushes, but I believe it does what it's supposed to do. Pushing now and asking for feedback before I forget I already did this work.
> Bug 975072 - Allow bugherder to tags comments when marking bugs

- .travis.yml
- package.json
Also adds a missing package.json `devDependency` on phantomjs, which would otherwise cause test failures under node v5 (since it ships with npm v3 which is more strict about peer dependencies).
> Switch Heroku and Travis to node v5.3.0

- test/mySpec.js
This test started failing when we stopped adding new b2g milestones to bugzilla (and in turn to bugherder). I say we just drop it.
> Drop the test for finding a b2g milestone for the current date since there are no such milestones anymore

- bugherder/js/Config.js
Drop b2g-inbound and fx-team branches.
Drop old esr branches.
Drop b2g release branches.
Add the upcoming esr52 branches.
Add autoland.
> Bug 1332293 - Update Bugherder's known trees

- bugherder/js/DebugUI.js
> Bug 1461208 - Only show bug number in debug UI if there is a bug number in the push data

- bugherder/js/FlagLoader.js
- test/mySpec.js
The tracking and status flags for Thunderbird have an underscore in their
names since Thunderbird 30. The resulting flags are cf_tracking_thunderbird_XX
and cf_status_thunderbird_XX. This is different than the assumption that there
is no underscore as is the case for the Firefox flags.
This sticks the additional underscore in the "productName" variable in FlagLoader
as that variable only gets used to generate the flag names.
> Bug 1658093 - Add underscore to Thunderbird tracking flag names.

- bugherder/thirdparty/bzjs/bz-0.4.3.js
REST endpoint got added in bug 1622867 and /latest/configuration will be
deprecated.
> Bug 1678132 - switch calls fetching bugzilla configuration to REST API. r=RyanVM

- bugherder/js/ConfigurationData.js
The milestones for bugzilla products have stopped being ordered in
https://bugzilla.mozilla.org/latest/configuration?flags=1
Bugherder has code to pick the milestone after the '---' one if no common
milestone has been detected (e.g. 'mozillaXX' and 'XX branch' with XX being
the version number). A check revealed this code only gets taken by the
'Mozilla Localizations' product nowadays which also has outdated milestone.
Let's drop the code.
> Bug 1693292 - remove code to set default milestone as option following '---' milestone. r=RyanVM
